x-environment: &mysql_environments
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: bennu

services:
  gunicorn:
    image: ghcr.io/hwakabh/bennu-official:latest
    # platform: linux/amd64
    environment:
      <<: *mysql_environments
      MYSQL_USER: root
      MYSQL_HOSTNAME: mysql
    container_name: gunicorn
    restart: always
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: bitnami/mysql:latest
    # platform: linux/amd64
    environment:
      <<: *mysql_environments
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    tty: true
    healthcheck:
      test: "mysqladmin ping || exit 1"
      interval: 5s
      retries: 3
    volumes:
      - mysql-data:/opt/bitnami/mysql/data

volumes:
  mysql-data:
