# https://nixpacks.com/docs/configuration/file

providers = ["python"]
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = ["gcc", "python312"]

[phases.build]
cmds = [
  "python manage.py migrate",
  "python manage.py loaddata initial_data",
  "python manage.py collectstatic --noinput --clear",
]

[start]
cmd = "gunicorn --config ./manifests/configs/gunicorn.conf.py"

[variables]
NIXPACKS_NO_CACHE='true'
