# For setting up kind cluster with local environment
# Be sure to confirm already installed docker in the laptop
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: bennu
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
