# Generated by Django 5.0 on 2024-01-16 10:52

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bennuhp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveschedule',
            name='with_actors',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=20), max_length=210, size=10),
        ),
    ]
