# Generated by Django 5.0 on 2023-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bennuhp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('venue', models.TextField()),
                ('descriptions', models.TextField(null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
