# Generated by Django 5.0 on 2023-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bennuhp', '0002_liveschedule_movie_music_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveschedule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='music',
            name='id',
        ),
        migrations.AlterField(
            model_name='liveschedule',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
