# Generated by Django 5.0 on 2023-12-19 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bennuhp', '0003_remove_liveschedule_id_remove_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveschedule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
