name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  # MYSQL_HOSTNAME: 127.0.0.1
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: bennu
  MYSQL_USER: root

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04
    # Need to use service-container since migrations will be called in Nixpacks builds
    services:
      db:
        image: bitnami/mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Security Test of Trivy with filesystem-mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './'
          trivy-config: .github/config/trivy.yaml
          # https://github.com/aquasecurity/trivy-action

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nixpacks CLI and build image
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash
          docker inspect $(docker ps -f ancestor=bitnami/mysql:latest -q)
          jq
          docker inspect $(docker ps -f ancestor=bitnami/mysql:latest -q) |jq -r '.[].NetworkSettings.IPAddress'
          nixpacks build . --name bennu-official:local \
            --env MYSQL_HOSTNAME=$(docker inspect $(docker ps -f ancestor=bitnami/mysql:latest -q) |jq -r '.[].NetworkSettings.IPAddress') \
            --env MYSQL_DATABASE=${{ env.MYSQL_DATABASE }} \
            --env MYSQL_ROOT_PASSWORD=${{ env.MYSQL_ROOT_PASSWORD }} \
            --env MYSQL_USER=${{ env.MYSQL_USER }}

      # Ref: https://github.com/iloveitaly/github-action-nixpacks/issues/6
      # - name: Build with Nixpack
      #   uses: iloveitaly/github-action-nixpacks@main
      #   env:
      #     MYSQL_HOSTNAME: ${{ env.MYSQL_HOSTNAME }}
      #     MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
      #     MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
      #     MYSQL_USER: ${{ env.MYSQL_USER }}
      #   with:
      #     push: false
      #     tags: |
      #       ${{ env.IMAGE_NAME }}:local
      #     # https://github.com/iloveitaly/github-action-nixpacks

      - name: Sanity Check with /healthz
        run: |
          docker compose up --build --detach && \
          docker run --network bennu-officialpage_default appropriate/curl -v -s --retry 3 --retry-connrefused -X GET http://gunicorn:8000/healthz ; echo
