name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  # MYSQL_HOSTNAME: 127.0.0.1
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: bennu
  MYSQL_USER: root

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Security Test of Trivy with filesystem-mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './'
          trivy-config: .github/config/trivy.yaml
          # https://github.com/aquasecurity/trivy-action

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Install nixpacks CLI and build image
      #   run: |
      #     curl -sSL https://nixpacks.com/install.sh | bash
      #     nixpacks build . --name bennu-official:local \
      #       --env MYSQL_HOSTNAME=db \
      #       --env MYSQL_DATABASE=${{ env.MYSQL_DATABASE }} \
      #       --env MYSQL_ROOT_PASSWORD=${{ env.MYSQL_ROOT_PASSWORD }} \
      #       --env MYSQL_USER=${{ env.MYSQL_USER }}

      # Does not require MySQL container inside Actions, since we have PR Environment with Railway
      - name: Build with Nixpack
        uses: iloveitaly/github-action-nixpacks@main
        with:
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:local
          # https://github.com/iloveitaly/github-action-nixpacks
