name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Security Test of Trivy with filesystem-mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './'
          trivy-config: .github/config/trivy.yaml
          # https://github.com/aquasecurity/trivy-action

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Nixpack
        uses: iloveitaly/github-action-nixpacks@main
        with:
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          # https://github.com/iloveitaly/github-action-nixpacks

      - name: Sanity Check with /healthz
        run: |
          docker compose up --build --detach && \
          docker run --network bennu-officialpage_default appropriate/curl -v -s --retry 3 --retry-connrefused -X GET http://gunicorn:8000/healthz ; echo
