name: "Pull Request Labeler"

on:
  pull_request_target:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
        configuration-path: .github/config/labeler.yaml
